### ISSUE TITLE
Add option to serve pre-compressed version of requested files

### ISSUE THREAD

**Issue by JonasGilg** [joseluisq/static-web-server#114]
**Is your feature request related to a problem? Please describe.**
Compressing files on the fly is sometimes slow. It would be great, if pre-compressed files could be served aswell.

**Describe the solution you'd like**
It would be great to have an option to serve a compressed version of the file, that is already on disk. So if `'Accept-Encoding': 'gzip'` is send the server would first try to find a compressed version on disk. Example:

Request `test.txt` with `'Accept-Encoding': 'gzip'`.
- Look for file `test.txt.gz`
- if found serve test.txt.gz
- else compress on the fly and serve

**Describe alternatives you've considered**

**Additional context**

**Comment by joseluisq** [comment]
Released on [v2.12.0](https://github.com/joseluisq/static-web-server/releases/tag/v2.12.0)
