### ISSUE TITLE
Support for URL customization

### ISSUE THREAD

**Issue by raj-magesh** [joseluisq/static-web-server#116]
I'd like to customize my URLs (e.g. `https://foo.com/bar.html` to `https://foo.com/pretty-bar`, or even `https://foo.com/logical/hierarchical/structure/pretty-bar`). Allowing arbitary mappings between URL requests and files on the server would be nice.

**Comment by joseluisq** [comment]
In fact, something like this is already on my TODO list which will make it possible to rewrite URLs via glob patterns at convenience.

**Comment by joseluisq** [comment]
Released on [v2.10.0](https://github.com/joseluisq/static-web-server/releases/tag/v2.10.0)
