### ISSUE TITLE
command line arg doesn't override config file

### ISSUE THREAD

**Issue by XyLyXyRR** [joseluisq/static-web-server#133]
**Describe the bug**
Command line arg doesn't override settings in config file

**To Reproduce**
Put `root = "./"` in config file, and try run `static-web-server -d web/`, it shows `./` instead of `web/`

**Expected behavior**
It shows `web/` when I passed `-d web/` to it.

**Logs/Screenshots**
If applicable, add logs or screenshots to help explain your problem.

**Environment and Specs**
 - static-web-server: 2.10.0
 - OS: Arch Linux x86_64, 5.15.60-1-lts
 - Docker: null
 - Client: 104.0.5112.79

**Additional context**

**Comment by joseluisq** [comment]
This functionality is intended by design. 
You can have a look at https://sws.joseluisq.net/configuration/config-file/#precendence

If you want to have CLI precedence then remove your option from the config file and just go with the CLI one.
