### ISSUE TITLE
Cache control policy for html is surprising and a bit hard to work around

### ISSUE THREAD

**Issue by marcusbuffett** [joseluisq/static-web-server#135]
I realized after setting up static-web-server to serve my website, that subsequent updates wouldn't be applied, and eventually found out that it was because html files are cached for one day by default. This seems a bit surprising, as standard practice afaik for web apps is to not cache the html. Since it was serving the cached html, it was fetching the old js too (from the <script> tags in the cached html), which either gets old javascript if that route is cached, or fails to fetch the js, if that's been cleared from the browser's cache. The version of my web app that I served had a pretty visible bug, so some users are stuck with that for a day. No big deal to me, just highlighting the negative effects of people running into this.

Maybe this is specific to my use case (SPAs), so not sure about default behavior. But the other side of this is that it's going to be somewhat difficult to work around with the current customization options. I think I'll have to add my own rules for cache control, since I can't use a glob pattern to match all requests for html (or maybe this is possible w/ glob patterns, but a quick search seems to suggest there's no way to say "requests that don't have an extension") to add a custom cache control header for that using the [custom http headers](https://sws.joseluisq.net/features/custom-http-headers/#examples). Ideally I'd like to just use the cache control stuff that's set up by default, but specify that html files shouldn't be cached.

Since setting up the --page-fallback thing and having no cache control for the html is going to be universal among SPAs, maybe a SPA mode that does both (and maybe there's other things to do) would make sense: 

```
static-web-server --spa
```

Anyway just rambling now, feel free to close if this seems irrelevant, there's no real bug here after all. Besides that one hiccup, this is an amazing project, I'm so happy to not have to tear my hair out over nginx. Super easy to setup and working flawlessly. Appreciate the hard work that's gone into it

EDIT: I've found out you can add meta tags to the html that serve the same purpose as disabling cache control headers, which makes this a non-issue for me. Again feel free to do nothing about this non-bug, just my experience and 2 cents.

**Comment by joseluisq** [comment]
I understand, also the glob pattern is sort of limited, so it works similarly to a  `.gitignore` file for example.

Anyway, if you're using _trailing slashes feature_ (default server behavior) then you could just use the glob below.

```toml
[advanced]

[[advanced.headers]]
source = "{*/,/*.html}"
[advanced.headers.headers]
Cache-Control = "no-cache"
```

Basically, `{*/,/*.html}` captures whatever directory request (E.g index pages) and other individual `html` file requests too.
Which means that a `localhost.com` (index), `localhost.com/assets/`, and `localhost.com/whatever.html` will fall into the `no-cache` header rule defined.

Otherwise, If you are not using trailing slashes then there is no way to work around this in the above direction. Only turning off the cache-control feature and going with the custom headers needed (by hand) would work.

Regarding not caching HTML files. It can be proposed so I'm open to discussing that in a separate issue.

BTW thanks for the support.

**Comment by marcusbuffett** [comment]
I may be not fully understanding, but I don't think that solution works for SPA stuff, since page-fallback is also used, so you want to match any arbitrary path that doesn't have an extension, but that's a clever workaround otherwise.

This is what I ended up with:

```
[general]
host = "::"
port = 80
root = "/public"
cache-control-headers = false
page-fallback = "/public/index.html"

[[advanced.headers]]
source = "*"
[advanced.headers.headers]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"

[[advanced.headers]]
source = "*.{js,css,png,jpg,jpeg}"
[advanced.headers.headers]
Cache-Control = "public, max-age=36000"
Pragma = ""
Expires = ""
```

Pretty sure this works perfectly for my use-case, just a little hacky. So yeah I'll close this out.

**Comment by joseluisq** [comment]
You're right, I missed the `page-fallback` option sorry.
Anyway, I think defining header rules by hand is not hacky since if users turn the default `cache-control-headers` off then this means essentially that those headers are now up to the users to define them if they want to.

**Comment by marcusbuffett** [comment]
Fair enough, the hacky comment was more about it being a "catch everything then make an exception for these", and that the headers can't be unset, just set to empty strings. Ofc having to set some headers is fine

**Comment by Venryx** [comment]
> I may be not fully understanding, but I don't think that solution works for SPA stuff, since page-fallback is also used, so you want to match any arbitrary path that doesn't have an extension, but that's a clever workaround otherwise.
> 
> This is what I ended up with:
> 
> ```
> [general]
> host = "::"
> port = 80
> root = "/public"
> cache-control-headers = false
> page-fallback = "/public/index.html"
> 
> [[advanced.headers]]
> source = "*"
> [advanced.headers.headers]
> Cache-Control = "no-cache, no-store, must-revalidate"
> Pragma = "no-cache"
> Expires = "0"
> 
> [[advanced.headers]]
> source = "*.{js,css,png,jpg,jpeg}"
> [advanced.headers.headers]
> Cache-Control = "public, max-age=36000"
> Pragma = ""
> Expires = ""
> ```
> 
> Pretty sure this works perfectly for my use-case, just a little hacky. So yeah I'll close this out.

If using Rust code to configure, here is its equivalent: (for the default-cache-control disabling, and header customization)
```rust
// override the default cache-control-headers (which simply keeps each resource for 24hr), to only use that caching for js/css/etc. files (most important: NOT caching the index.html file, whether requested directly or as fallback)
opts.general.cache_control_headers = false;
let compile_glob = |str: &str| GlobBuilder::new(str).build().unwrap().compile_matcher();
opts.advanced = Some(Advanced {
	headers: Some(vec![
		Headers { source: compile_glob("*"), headers: headers_for_no_caching() },
		Headers { source: compile_glob("*.{js,css,png,jpg,jpeg}"), headers: headers_for_caching_for_x_seconds(36000) },
	]),
	..Default::default()
});

fn headers_for_no_caching() -> HeaderMap {
	let mut headers = HeaderMap::new();
	headers.insert("Cache-Control", "no-cache, no-store, must-revalidate".parse().unwrap());
	headers.insert("Pragma", "no-cache".parse().unwrap());
	headers.insert("Expires", "0".parse().unwrap());
	headers
}
fn headers_for_caching_for_x_seconds(seconds: u64) -> HeaderMap {
	let mut headers = HeaderMap::new();
	headers.insert("Cache-Control", format!("public, max-age={}", seconds).parse().unwrap());
	headers.insert("Pragma", "".parse().unwrap());
	headers.insert("Expires", "".parse().unwrap());
	headers
}
```

In my case, I actually customized the caching to the following:
```rust
// base caching: no caching
Headers { source: compile_glob("*"), headers: headers_for_no_caching() },

// caching for files with extensions of 1-4 characters long: cache for one day
Headers { source: compile_glob("*.[!/]"), headers: headers_for_caching_for_x_seconds(36000) },
Headers { source: compile_glob("*.[!/][!/]"), headers: headers_for_caching_for_x_seconds(36000) },
Headers { source: compile_glob("*.[!/][!/][!/]"), headers: headers_for_caching_for_x_seconds(36000) },
Headers { source: compile_glob("*.[!/][!/][!/][!/]"), headers: headers_for_caching_for_x_seconds(36000) },

// caching for .html files: no caching
Headers { source: compile_glob("*.html"), headers: headers_for_no_caching() },
```

I like this a bit better because it avoids caching `.html` and extension-less URLs, while caching everything else. [**EDIT**: My initial response had globs that were incorrect. After posting, I noticed the cache-control headers weren't being set for URLs where they should have been. I then looked more closely at the docs, corrected the glob patterns, and have confirmed they now work how described/wanted.]

Also note that, in order to construct the `GlobBuilder` and `HeaderMap` structs, you need to add the `globset` and `http` crates as dependencies, and make sure the version you request matches what `static-web-server` requests:
```toml
static-web-server = "2.36.0"
globset = { version = "0.4", features = ["serde1"] } # match version+features specified by static-web-server
http = "0.2" # match version specified by static-web-server
```
