### ISSUE TITLE
Much slower than sfz

### ISSUE THREAD

**Issue by jonashaag** [joseluisq/static-web-server#146]
Just a random, single data point: I've compared req/s to https://github.com/weihanglo/sfz with a specific setup:

- Request ~ 3k files via `curl --http2 --parallel`
- Total downloaded size is ~ 6 GB

Req/s or GB/s with sfz is roughly 3x better than with static-web-server.

Using HTTP/2 doesn't make a difference.

Version: static-web-server 2.11.0

curl output of a single download:

```
sfz:
...
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< server: sfz/0.7.1
< cache-control: public, max-age=0
< last-modified: Sun, 21 Aug 2022 15:09:17 GMT
< etag: "1661094557-12909"
< accept-ranges: bytes
< content-type: application/x-bzip2
< transfer-encoding: chunked
< date: Sun, 25 Sep 2022 19:58:36 GMT

static-web-server:
...
< HTTP/1.1 200 OK
< content-length: 12909
< content-type: application/x-bzip2
< accept-ranges: bytes
< last-modified: Sun, 21 Aug 2022 15:09:17 GMT
< cache-control: public, max-age=31536000
< date: Sun, 25 Sep 2022 20:02:44 GMT
```

**Comment by joseluisq** [comment]
Thanks for that. Sure we could do it better. And yeah, there are some parts that need help regarding performance/optimizations. Happy to receive contributions.

BTW here is a similar comparison time ago https://github.com/joseluisq/static-web-server/issues/90

**Comment by jtackaberry** [comment]
A while back I had also compared sws to https://github.com/mufeedvh/binserve and similarly found that sws was significantly slower.  (I forget the specifics but IIRC it was nearly an order of magnitude.)  And binserve provides quite a number of more advanced features such as templating.

**Comment by joseluisq** [comment]
FYI since the performance was improved in the latest [v2.13.1](https://github.com/joseluisq/static-web-server/releases/tag/v2.13.1). I would appreciate your feedback.

**Comment by jtackaberry** [comment]
@joseluisq  after a very hasty and crude test that serves up a plaintext file with 4 bytes (just containing the text `pong`) and fetches it with `wrk` for 10 seconds, indeed the performance improvement looks great.

* binserve v0.2.0: ~61k req/s
* sws v2.13.0: ~17k req/s
* sws v2.13.1: ~106k req/s

Full output below.  Great work, Jose!

```bash
# binserve v0.2.0
$ wrk -c 500 -t 12 -d 10s http://127.0.0.1:1337/assets/ping
Running 10s test @ http://127.0.0.1:1337/assets/ping
  12 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    14.35ms   16.05ms  62.90ms   78.37%
    Req/Sec     5.13k   721.35     9.47k    74.46%
  617898 requests in 10.10s, 191.05MB read
Requests/sec:  61179.32
Transfer/sec:     18.92MB

# sws v2.13.0
$ wrk -c 500 -t 12 -d 10s http://127.0.0.1:1337/assets/ping
Running 10s test @ http://127.0.0.1:1337/assets/ping
  12 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    27.96ms    8.37ms  91.63ms   74.12%
    Req/Sec     1.46k   219.97     6.78k    93.83%
  172234 requests in 10.10s, 37.13MB read
Requests/sec:  17053.49
Transfer/sec:      3.68MB

# sws v2.13.1
$ wrk -c 500 -t 12 -d 10s http://127.0.0.1:1337/assets/ping
Running 10s test @ http://127.0.0.1:1337/assets/ping
  12 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.53ms    2.41ms 211.63ms   72.31%
    Req/Sec     8.94k     1.65k   38.53k    91.37%
  1071886 requests in 10.10s, 231.02MB read
Requests/sec: 106130.52
Transfer/sec:     22.87MB
```

**Comment by joseluisq** [comment]
@jtackaberry awesome! also resources-wise, this improvement should be also a big win.
