### ISSUE TITLE
Question regarding the benchmarks

### ISSUE THREAD

**Issue by mufeedvh** [joseluisq/static-web-server#156]
Hey @joseluisq, I am the author of [binserve](https://github.com/mufeedvh/binserve) and I have a question regarding how binserve is represented in the benchmarks. The benchmarks on binserve seems to be very low on the chart represented here and I want to know how you got that result.

Just wanted to know the benchmark setup and clarify whether the numbers I am looking at are accurate. And if you have some ideas on why that might be, please let me know what I am missing so I can improve my project based on that. :raised_hands: 

> **SIDE NOTE:** I am assuming https://github.com/static-web-server/static-web-server/issues/146#issuecomment-1257398643 is the same question.

I ran a benchmark on my system to confirm and binserve is 2x times faster.

## My results:

**static-web-server:**

```
λ wrk -c 500 -t 12 -d 5 http://127.0.0.1:8888/
Running 5s test @ http://127.0.0.1:8888/
  12 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.05ms    1.73ms 203.91ms   88.75%
    Req/Sec    10.72k     4.07k   29.81k    65.50%
  644478 requests in 5.06s, 134.60MB read
Requests/sec: 127262.62
Transfer/sec:     26.58MB
```

![Screenshot from 2022-10-27 20-48-41](https://user-images.githubusercontent.com/26198477/198331373-f0696fdc-f179-46f6-880f-6835217914e9.png)

**binserve:**

```
λ wrk -c 500 -t 12 -d 5 http://127.0.0.1:1337/
Running 5s test @ http://127.0.0.1:1337/
  12 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.04ms  332.47us  17.19ms   91.34%
    Req/Sec    19.90k     3.74k   78.95k    99.34%
  1193903 requests in 5.10s, 247.08MB read
Requests/sec: 234104.96
Transfer/sec:     48.45MB
```

![Screenshot from 2022-10-27 20-54-08](https://user-images.githubusercontent.com/26198477/198331789-fde49c5e-7e7c-4203-9126-a4d2af38dbe5.png)

And I checked this project out and it's really cool, loved how simplistic and straight to the point it is!

**Comment by joseluisq** [comment]
Hey @mufeedvh!
Great that you have taken the time to provide more binserve insights. I appreciate it!

> **binserve:**
> 
> ```
> λ wrk -c 500 -t 12 -d 5 http://127.0.0.1:1337/
> Running 5s test @ http://127.0.0.1:1337/
>   12 threads and 500 connections
>   Thread Stats   Avg      Stdev     Max   +/- Stdev
>     Latency     2.04ms  332.47us  17.19ms   91.34%
>     Req/Sec    19.90k     3.74k   78.95k    99.34%
>   1193903 requests in 5.10s, 247.08MB read
> Requests/sec: 234104.96
> Transfer/sec:     48.45MB
> ```

That looks cool! Honestly, I wanted to find some web servers to kind of measure SWS against them in order to improve SWS performance path in the future.

That said,
Did you check the [benchmark **setup** page](https://github.com/static-web-server/static-web-server/blob/master/benchmark/BENCHMARKS.md#web-servers-setup)?

I decided to join binserve to the benchmark's party but under the "same" conditions as SWS has. That means no in-memory cache for example since SWS and the other servers don't have it (at least for this benchmark).

Below is what I mean. I turn those binserve features off before benchmarking:

binserve 0.2.0
- fast_mem_cache=false
- enable_hot_reload=false
- enable_logging=false
- enable_directory_listing=false

I share with you the `binserve.json` file that I used for that benchmark.

```json
{
    "server": {
        "host": "127.0.0.1:1337",
        "tls": {
            "host": "127.0.0.1:443",
            "enable": false,
            "key": "key.pem",
            "cert": "cert.pem"
        }
    },

    "routes": {
        "/": "public/index.html",
        "/usage": "public/usage.hbs"
    },

    "static": {
        "directory": "public/assets",
        "served_from": "/assets",
        "error_pages": {
            "404": "public/404.html"
        }
    },

    "template": {
        "partials": {
            "header": "public/header.hbs"
        },
        "variables": {
            "app_name": "Binserve"
        }
    },

    "config": {
        "enable_hot_reload": false,
        "fast_mem_cache": false,
        "enable_cache_control": true,
        "enable_directory_listing": false,
        "minify_html": false,
        "follow_symlinks": false,
        "enable_logging": false
    },

    "insert_headers": {
        "x-greetings": "hellooo!"
    }
}
```

Please let me know if I'm doing something wrong here. If so then please suggest what you think is convenient and I will update the benchmark page and graph accordingly. You know those are just "benchmarks" :sweat_smile:

**Comment by joseluisq** [comment]
> And I checked this project out and it's really cool, loved how simplistic and straight to the point it is!

Awesome! I only can say that SWS is mostly driven by the community's feedback and suggestions which is huge!

I also love binserve's features specially Templating (hbs) and In-Memory cache. Yes, I would like to have such a feature too, someday xD.

**Comment by mufeedvh** [comment]
Hey @joseluisq, thanks for the quick response. Yeah that makes total sense, my bad I didn't read the setup part properly. Binserve does not play much role in performance when the `fast_mem_cache` is turned off since it fallbacks to the [`NamedFile`](https://docs.rs/actix-files/latest/actix_files/struct.NamedFile.html) implementation Actix has.

> I decided to join binserve to the benchmark's party but under the "same" conditions as SWS has. That means no in-memory cache for example since SWS and the other servers don't have it (at least for this benchmark).

Regarding this, some servers does use in-memory caching under certain conditions for improved performance, sort of like an LRU cache. For example, here is NGINX's implementation of file caching:

- https://github.com/nginx/nginx/blob/master/src/core/ngx_open_file_cache.c
- https://www.nginx.com/blog/cache-placement-strategies-nginx-plus#Where-is-Cached-Data-Stored

So these kind of ambiguities are there.

I was just surprised to see the numbers hence why I opened this issue, didn't notice the configuration change :sweat_smile:. I think in this scenario, it would be cool if you could label binserve with `binserve (fast_mem_cache: off)` in the benchmarks graphs to avoid any confusion. :raised_hands: 

> You know those are just "benchmarks"

Haha yeah, I was just concerned like looking at a child's poor grades in a report card lol, just wanted the clarification and got it! Thank you! :heart::raised_hands:

**Comment by joseluisq** [comment]
> Hey @joseluisq, thanks for the quick response. Yeah that makes total sense, my bad I didn't read the setup part properly. Binserve does not play much role in performance when the `fast_mem_cache` is turned off since it fallbacks to the [`NamedFile`](https://docs.rs/actix-files/latest/actix_files/struct.NamedFile.html) implementation Actix has.
> 
> >

I see, no worries, I got it.

> Regarding this, some servers does use in-memory caching under certain conditions for improved performance, sort of like an LRU cache. For example, here is NGINX's implementation of file caching:
> 
> * https://github.com/nginx/nginx/blob/master/src/core/ngx_open_file_cache.c
> * https://www.nginx.com/blog/cache-placement-strategies-nginx-plus#Where-is-Cached-Data-Stored
> 
> So these kind of ambiguities are there.

Wow, I didn't know that. It bit my curiosity, I will investigate more!

> I was just surprised to see the numbers hence why I opened this issue, didn't notice the configuration change . I think in this scenario, it would be cool if you could label binserve with `binserve (fast_mem_cache: off)` in the benchmarks graphs to avoid any confusion.

Fair enough!
Sorry if the benchmark was too raw. I will prepare a PR that points that out clearly on the page as well as in the graph.
But I also think that definitely we will need a second graph in the future if SWS gets an in-memory cache feature someday.

> > You know those are just "benchmarks"
> 
> Haha yeah, I was just concerned like looking at a child's poor grades in a report card lol, just wanted the clarification and got it! Thank you! heartraised_hands

Haha yeah as I said I don't want to appear like the next-door rude man.
Please, thank you for taking the time and clarify that. :+1:
