### ISSUE TITLE
Add Android targets support

### ISSUE THREAD

**Issue by denisidoro** [joseluisq/static-web-server#163]
**Is your feature request related to a problem? Please describe.**
The releases don't include a binary for Android. 

**Describe the solution you'd like**
To change the workflow yaml to include it 

**Describe alternatives you've considered**
My fork (https://github.com/denisidoro/static-web-server) includes it. I completely changed the yaml file to make it work, though. That's why I'm not submitting a pull request here: I suppose you'll want to add support for this with minimal changes. 

**Additional context**
The binary can be used in e.g. Termux

**Comment by joseluisq** [comment]
Why not. But it should be interesting if you can tell a bit about the use case here with a new Android target(s).

**Comment by joseluisq** [comment]
Also, it should be great to describe which Android targets are you interested in.

**Comment by denisidoro** [comment]
> use case

I use an old phone as a raspberry Pi-like device. It has an FTP server, DLNA server and HTTP server.

> targets

Mainly aarch64. armv7 would be a plus, for older devices.

**Comment by joseluisq** [comment]
This is done now via https://github.com/static-web-server/static-web-server/pull/194.

Unfortunately, SWS does not build for ARMv7 due to https://github.com/mitsuhiko/listenfd/issues/16.
So, if there is more clarity in the future on how to fix that then we could include `armv7-linux-androideabi`.
