### ISSUE TITLE
File type detection for cache control headers is suboptimal

### ISSUE THREAD

**Issue by mfontanini** [joseluisq/static-web-server#174]
The [code](https://github.com/static-web-server/static-web-server/blob/master/src/control_headers.rs#L20-L40) that currently detects the file type for a URI and maps it to a max age value is suboptimal. It's performing one memory allocation ("." + file type) for every defined file type. 

A better way of doing this is to first find the file type in the URI and then search for it in each file type slice. This would in turn perform 0 allocations.

**Comment by joseluisq** [comment]
Resolved by #175
