### ISSUE TITLE
Publish to crates.io to allow use as a library

### ISSUE THREAD

**Issue by da2ce7** [joseluisq/static-web-server#188]
Hello @joseluisq

In one of our projects we would like to use this project as a library and programmatically call the [`fn run_server_on_rt`](https://github.com/static-web-server/static-web-server/blob/master/src/server.rs#L64) function from our own rust-wrapper.

However, we could not find this project published on [crates.io](https://crates.io/).

Maybe @Absolucy , who controls the "[sws](https://crates.io/crates/sws)" name, or @NoahJelen who controls the "[simple-web-server](https://crates.io/crates/simple-web-server)" name could offer to transfer the ownership to you for this project.

This would make lots of sense for our particular use-case, so we would prefer not to use a script: https://github.com/torrust/torrust-index-frontend/pull/68

Kind Regards,
Cameron.

**Comment by joseluisq** [comment]
In fact, I was thinking about this idea a couple of times in the past.
I'm aware that it can help people like you and others embed SWS with ease and even opt-in/out features on demand to do their own stuff.

So, why not.
However, I probably will need some help regarding how to make SWS modules library-wise like what API parts expose, better structure, refactorings, docs, setup, etc. Which definitely will take time.

Regarding the name, I think will be not a big deal, we could even go with something like `libsws`.

So, If you would like to help, more than welcome!

**Comment by joseluisq** [comment]
Just to clarify #189 is one of the steps forward to make `libsws` happen.

FYI, I will take care of preparing the API for the library, doing the refactorings needed as well as adding proper documentation for the API exposed.

**Comment by joseluisq** [comment]
FYI there is an ongoing effort for this on #190. If you think we could improve that then just let me know.

**Comment by joseluisq** [comment]
SWS is in general ready to be published in crates.io as `static_web_server`. However, this is something that will eventually happen in a couple of weeks with the next SWS release.

In the meantime, I left some considerations to take on the https://github.com/static-web-server/static-web-server/pull/190#issue-1643067666 description.

**Comment by da2ce7** [comment]
@joseluisq for our testing purposes, it would be very useful if you could soon-publish an alpha release to crates.io, so we can prepare our own release process. :)

**Comment by joseluisq** [comment]
@da2ce7 Sure, I will publish it in the coming hours, stay tuned.

**Comment by joseluisq** [comment]
SWS is on crates.io as beta. https://crates.io/crates/static-web-server
Enjoy!
