### ISSUE TITLE
Add support for zstd encoder

### ISSUE THREAD

**Issue by gaby** [joseluisq/static-web-server#193]
**Describe the solution you'd like**
Currently SWS only supports brotli, deflate, and gzip. The async_compression library has support for zstd which would be beneficial when SWS is used in combination with other Rust tools, Ex. Vector.dev

https://docs.rs/async-compression/latest/async_compression/#compression-algorithm

**Comment by joseluisq** [comment]
Just out of curiosity. Can you please elaborate a bit more about what's your use case for zstd as a new content encoding?

**Comment by gaby** [comment]
@joseluisq Adding zstd as a content encoder can lead to faster load times, improved user experience, reduced bandwidth costs, and increased energy efficiency. These benefits make zstd an excellent choice for modern web services looking to optimize their performance and deliver the best possible experience to users.

There's several study cases explaining how zstd is used on service to service communications to reduce network i/o usage compared to gzip/brotli

Sources:
- https://aws.amazon.com/blogs/containers/reducing-aws-fargate-startup-times-with-zstd-compressed-container-images/
- https://docs.aws.amazon.com/athena/latest/ug/compression-support-zstd-levels.html
- https://engineering.fb.com/2018/12/19/core-data/zstandard/
- http://www.bioinformaticszen.com/post/use-zstd-for-raw-fastq/
- https://daniel.haxx.se/blog/2020/08/19/curl-7-72-0-more-compression/

I'm currently using Caddy 2 to serve static content with zstd encoding. For some use cases using something like SWS would be ideal, even more if I could serve the content using zstd.

**Comment by joseluisq** [comment]
Ok, I got it.
Then, I think it can be used for backend-to-backend communication and backend-to-native-mobile/desktop apps.
I also saw that the QUIC protocol is including support for zstd (maybe browsers someday too).

Since Zstd looks can provide a good balance between compression ratio and decompression speed so why not.

Also noting that we could add on-the-fly zstd compression and pre-compressed file serving in a similar way to how is done for gzip/brotli actually.

**Comment by gaby** [comment]
@joseluisq It's slowly starting to get added everywhere. There's an issue open to add support for zstd in Firefox.

Browser tester: https://www.daniel.priv.no/tools/zstd-browser-test/
- Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1301878
- Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1246971

**Comment by joseluisq** [comment]
Also, I recently noted that the Zstandard compression format for `Content-Encoding` positions has already started for major browsers. So it looks like the zstd adoption continues growing.

- Firefox: https://github.com/mozilla/standards-positions/issues/775
- WebKit: https://github.com/WebKit/standards-positions/issues/168
- Chrome: Interested and under evaluation

**Comment by gaby** [comment]
@joseluisq Awesome finds! Looking forward!

**Comment by joseluisq** [comment]
Done. Check out #197 tests to know what it looks like.

Also, I created https://github.com/joseluisq/alpine-curl if someone wants to test SWS / Zstd requests.

**Comment by gaby** [comment]
@joseluisq Thank you, looking forward to testing this out!
