### ISSUE TITLE
Help needed with tls_redirect_from feature in V2 version

### ISSUE THREAD

**Issue by micsama** [joseluisq/static-web-server#202]
I have read in #26 that your program supports tls_redirect_from feature in V1 version to redirect http to https. I would like to know how to use this feature in the current V2 version. Any help would be appreciated.

**Comment by joseluisq** [comment]
That's correct, TLS redirection is present in v1 but unfortunately not in the latest v2.
So for now, what you can do is stay with v1 for a while.

However, this feature is on my TODO list, so there might be a chance to promote it to be a thing on the next minor release if I get the time for but not guaranteed.

**Comment by micsama** [comment]
> That's correct, TLS redirection is present in v1 but unfortunately not in the latest v2. So for now, what you can do is stay with v1 for a while.
> 
> However, this feature is on my TODO list, so there might be a chance to promote it to be a thing on the next minor release if I get the time for but not guaranteed.

Thank you for your prompt response. I appreciate the information you provided regarding the tls_redirect_from feature. It's good to know that it was present in V1, and I understand that it might not be available in the current V2 version.

I'll consider staying with V1 for the time being, as you suggested. It's great to hear that the feature is on your TODO list, and I'm looking forward to the possibility of it being included in a future release. I understand that it's not guaranteed, but I appreciate your consideration of this feature.

Thank you again for your help, and I wish you continued success with your project.

Best regards,

**Comment by joseluisq** [comment]
Ready for the next minor release.
More details on the PR https://github.com/static-web-server/static-web-server/pull/203#issue-1709107005

**Comment by joseluisq** [comment]
Released on [v2.17.0](https://github.com/static-web-server/static-web-server/releases/tag/v2.17.0)
