### ISSUE TITLE
v2.19.0 release files seem corrupted

### ISSUE THREAD

**Issue by mac-chaffee** [joseluisq/static-web-server#224]
**Describe the bug**
At least one of the v2.19.0 release files seems corrupted, `static-web-server-v2.19.0-armv7-unknown-linux-musleabihf.tar.gz`

**To Reproduce**

```
$ curl -iSsLO https://github.com/static-web-server/static-web-server/releases/download/v2.19.0/static-web-server-v2.19.0-armv7-unknown-linux-musleabihf.tar.gz
$ tar -xzf static-web-server-v2.19.0-armv7-unknown-linux-musleabihf.tar.gz
tar: Error opening archive: Unrecognized archive format


$ curl -iSsLO https://github.com/static-web-server/static-web-server/releases/download/v2.19.0/static-web-server-v2.19.0-SHA256SUM
$ sha256sum -c ./static-web-server-v2.19.0-SHA256SUM 2>&1 | grep armv7
static-web-server-v2.19.0-armv7-unknown-linux-musleabihf.tar.gz: FAILED
$ sha256sum ./static-web-server-v2.19.0-armv7-unknown-linux-musleabihf.tar.gz
c9a012557dd6f682101ad23675e8a31c15a6762ba3a9313c7ae36e921a92df07  ./static-web-server-v2.19.0-armv7-unknown-linux-musleabihf.tar.gz
```

**Environment and Specs**
 - static-web-server: v2.19.0
 - OS: MacOS

**Comment by mac-chaffee** [comment]
Ah, it's the `-i` flag, shouldn't have had that. Why does curl put that part in the -O file...?

**Comment by joseluisq** [comment]
> Ah, it's the `-i` flag, shouldn't have had that. Why does curl put that part in the -O file...?

I don't know why curl put `-i` when downloading files using`-O`.
But those together will result in a file with HTTP headers content combined. 
So AFAICT omitting `-i` or just being more explicit with `-o <file-name>` should work as expected.
