### ISSUE TITLE
Remove .html extension from pages

### ISSUE THREAD

**Issue by bubnenkoff** [joseluisq/static-web-server#228]
It seems that currently not possible:
To remove the `.html` extension from a URL. For example: 
From  
```
example.com/content.html
```
To 
```
example.com/content
```

I would like to have this future.

**Comment by joseluisq** [comment]
You could achieve this using [`URL Rewrites`](https://static-web-server.net/features/url-rewrites/) via a config file.

For example

```toml
[[advanced.rewrites]]
source = "/content.html"
destination = "/content"
```

However, URL Rewrites at this point are limited. For example, `destination` does not support placeholders yet, making it not possible to define generic rewrites. Another limitation is that there is no redirection support for rewrites yet.

I believe that when the URL Rewrites limitations get resolved then your use case should be covered.

**Comment by joseluisq** [comment]
Our latest [v2.20.0](https://github.com/static-web-server/static-web-server/releases/tag/v2.20.0) already makes possible generic route rewrites with optional redirection so you can easily remove file extensions if you want.
You can read more about it at https://static-web-server.net/features/url-rewrites/
