### ISSUE TITLE
add a silent /health for k8s probes

### ISSUE THREAD

**Issue by glehmann** [joseluisq/static-web-server#237]
**Is your feature request related to a problem? Please describe.**

I get a lot of logs from the liveness probe in kubernetes, as discussed in https://github.com/static-web-server/static-web-server/discussions/236

**Describe the solution you'd like**

@joseluisq suggested that a silent /health could be a solution — I agree with that.

**Describe alternatives you've considered**

Using a HEAD request on /, but k8s doesn't (yet) support that in probes.

**Additional context**
Add any other context or screenshots about the feature request here if needed.

**Comment by joseluisq** [comment]
Resolved by https://github.com/static-web-server/static-web-server/pull/238
