### ISSUE TITLE
Unable to start the server via Wasmer - Not supported (os error 58)

### ISSUE THREAD

**Issue by iamshreeram** [joseluisq/static-web-server#249]
**Describe the bug**
Trying to run the static-web-server via `wasmer` with port `9001`.

**To Reproduce**
1. Open iterm2 in macOS
2. Install `wasmer` and run the below command 
```
wasmer run wasmer/static-web-server -- --port 9001
```
3. You will see error while starting up the server 

**Expected behavior**
Start and run the static-web-server in port 9001

**Logs/Screenshots**
```
2023-08-02T17:49:30.005430Z ERROR static_web_server::server: server failed to start up: failed to bind to [::]:9001 address

Caused by:
    Not supported (os error 58)
```

**Environment and Specs**
 - static-web-server: via wasmer
 - OS: Macos 13.4.1
 - Client: Firefox 115.0

**Additional context**
No other apps are using the port 9001. I couldn't run the app from any port.

**Comment by joseluisq** [comment]
Clarify that we do not officially support Wasm/Wasix targets **yet**. See [docs](https://static-web-server.net/platforms-architectures/).
Wasmer folks added support for SWS via a [fork](https://github.com/wasix-org/static-web-server) for now ([wasmer/static-web-server](https://wasmer.io/wasmer/static-web-server)).

However, SWS project will eventually support `wasix` target in a not remote future. So stay tuned.

**Comment by joseluisq** [comment]
About the Wasmer error.
You have to enable Wasmer's `net` and `threads` features as well as map your host dir via the `mapdir` option before starting the server.

```sh
wasmer run wasmer/static-web-server --net --enable-threads --mapdir /public:/my/host/dir -- --port 9001 
```

See [wasix-axum](https://wasix.org/docs/language-guide/rust/tutorials/wasix-axum) example for more details.

**Comment by joseluisq** [comment]
Closing because this is not an SWS issue and we still don't support Wasm/Wasix targets.
