### ISSUE TITLE
Custom index file

### ISSUE THREAD

**Issue by moinologics** [joseluisq/static-web-server#257]
you provide customisation through SERVER_ROOT env variable which is good, but what about SERVER_INDEX_FILE? if someone want to have different name than index.html for default file. please provide this ENV variable

**Comment by joseluisq** [comment]
Probably something similar to what Nginx Index module does like `index index.html index.htm;` for all requests ending with the slash.

We could go with something like:

```sh
SERVER_INDEX_FILES="index.html index.htm etc" 
```

**Comment by moinologics** [comment]
Yes 👍

**Comment by joseluisq** [comment]
Already done and should be shipped in the next v2.23.0.

**Comment by joseluisq** [comment]
Resolved in [v2.23.0](https://github.com/static-web-server/static-web-server/releases/tag/v2.23.0)
