### ISSUE TITLE
Too wide table in directory listing for long file names

### ISSUE THREAD

**Issue by northern-mindset** [joseluisq/static-web-server#259]
**Describe the bug**
When the file names are long, the modification date and size columns are pushed off the designated page width.

**To Reproduce**

- Add a file with a long enough name.

**Expected behavior**

The file name gets truncated with ellipsis to give space to the other columns.

**Logs/Screenshots**

(longest files are much below)

![image](https://github.com/static-web-server/static-web-server/assets/6065071/caa1b986-50f8-4105-ab6f-fdd82c291fb4)

Adding `table-layout: fixed` to the `table` styling helps:

![image](https://github.com/static-web-server/static-web-server/assets/6065071/f95d1ec5-ffdf-4462-81dc-5d1703d0b796)

But doesn't work well on smaller screens:

![image](https://github.com/static-web-server/static-web-server/assets/6065071/dbeb02ee-1e8a-40f7-9dd6-ab51b0a6b45e)

I'm not sure where to go from here.

**Environment and Specs**
 - static-web-server: v2.21.1
 - OS: Ubuntu 22.04
 - Docker: 24.0.5
 - Client: Firefox 117

**Comment by joseluisq** [comment]
Done in #260. There is also a video of what will look like.

You can also test it using the devel Docker images.
 
- joseluisq/static-web-server:devel
- joseluisq/static-web-server:devel-alpine
- joseluisq/static-web-server:devel-debian

**Comment by northern-mindset** [comment]
Works nicely in v2.22.0. :pray:
