### ISSUE TITLE
add webdav support

### ISSUE THREAD

**Issue by Dialga** [joseluisq/static-web-server#262]
**Is your feature request related to a problem? Please describe.**
So files can be added/created/modified in windows explorer

**Describe the solution you'd like**
builtin webdav support would be nice

**Describe alternatives you've considered**
dufs web server, https://github.com/filebrowser/filebrowser.

**Additional context**
Add any other context or screenshots about the feature request here if needed.

**Comment by joseluisq** [comment]
SWS is basically a web server that **focuses** on serving static files but is not a file manager.
So in that sense. Unfortunately, I do not see Webdav being a feature for SWS. 
Unless you have a strong opinion on why Webdav should be considered as a feature.
Maybe Webdav could be a thing in the future, who knows but definitely not in the current stable.
