### ISSUE TITLE
Maintenance mode custom file not working with env var

### ISSUE THREAD

**Issue by tuxpizza** [joseluisq/static-web-server#276]
Hey, thanks for the addition of the maintenance feature, however I seem to be having a problem which I can't figure out with the custom file part. 

**To Reproduce**
Tried this on a couple different systems (TrueNAS Scale and Ubuntu using Docker Compose) but unfortunately the environmental variable SERVER_MAINTENANCE_MODE_FILE is not working.

Instead of showing the file that I listed, it still shows the default "The server is under maintenance mode" text.
I tried both the current path and absolute path for the file.

**Logs/Screenshots**

Env vars I am using in my docker-compose.yml

`     - SERVER_PORT=99
      - SERVER_ROOT=/public
      - SERVER_MAINTENANCE_MODE=true
      - SERVER_MAINTENANCE_MODE_FILE=./test.html
`

No errors in the console, and it confirms my env var.
`static-web-1  | 2023-10-19T18:09:52.979341Z  INFO static_web_server::info: maintenance mode: enabled=true
static-web-1  | 2023-10-19T18:09:52.979343Z  INFO static_web_server::info: maintenance mode status: 503
static-web-1  | 2023-10-19T18:09:52.979344Z  INFO static_web_server::info: maintenance mode file: "./test.html"
static-web-1  | 2023-10-19T18:09:52.979418Z  INFO static_web_server::info: http1 server is listening on http://[::]:99
static-web-1  | 2023-10-19T18:09:52.979426Z  INFO static_web_server::info: press ctrl+c to shut down the server
`

**Environment and Specs**
 - static-web-server: 2.23.0
 - Docker: 24.0.6

**Comment by joseluisq** [comment]
`SERVER_MAINTENANCE_MODE_FILE` is an independent file path and not relative to the `SERVER_ROOT`.

That means SWS will default to the generic message when either the `SERVER_MAINTENANCE_MODE_FILE` is empty or the file can not be found.

So in your case, you just need to go with absolute paths to fix the issue like:

```env
SERVER_MAINTENANCE_MODE_FILE=/public/test.html
```

But definitely I will improve the logging information and the docs to be more explicit.

**Comment by tuxpizza** [comment]
Ah yes that did it! Thank you!

**Comment by joseluisq** [comment]
There is an improvement about this for the next release
https://github.com/static-web-server/static-web-server/pull/282
