### ISSUE TITLE
cors

### ISSUE THREAD

**Issue by techo207** [joseluisq/static-web-server#289]
Thanks for this awesome tool,

**Describe the bug**
I am trying to render a file from my directory inside an Iframe but i'm getting this cors error due missing header in response

Access to fetch at 'http://localhost:10250/' from origin 'http://localhost:8123' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**To Reproduce**
run this command 
./static-web-server-macos --port '10250' --root 'XXX'  -c='http://localhost:10250'

and then try to fetch 
![image](https://github.com/static-web-server/static-web-server/assets/13383372/0b505b15-df71-433f-89f8-97536da54e2a)

![image](https://github.com/static-web-server/static-web-server/assets/13383372/781b9fa3-d1d4-4f40-a243-2b325680a824)

In the log I can see the origin being setting 

![image](https://github.com/static-web-server/static-web-server/assets/13383372/e2a870d7-826e-4c85-852e-e106304ff985)

**Expected behavior**
it should have Access-Control-Allow-Origin header

**Environment and Specs**
 - static-web-server: 2.24.0
 - OS: Macos 13.4
 - Client: Chrome, Postman

**Comment by joseluisq** [comment]
It is not clear to me how are you using SWS and how the resources are being requested but I did a quick test of CORS in general and works as expected.

If you are not sure how to test CORS with SWS then have a look at the examples of this PR https://github.com/static-web-server/static-web-server/pull/87

Also please check these documentation pages:
- https://static-web-server.net/features/cors/ (I assume that you already checked this)
- https://static-web-server.net/features/http-methods/#preflight-requests-in-cors (for testing SWS instance)

I'm going to close the issue.
If you want to discuss this further or if you have a better way to reproduce your issue just me know.
