### ISSUE TITLE
Range requests do not allow overshoot (but is commonly accepted)

### ISSUE THREAD

**Issue by bjornharrtell** [joseluisq/static-web-server#295]
### Search for duplicate feature request

- [X] I already searched, and this feature request or improvement is not a duplicate.

### Feature scope

Improve existing functionality

### Feature request related to a problem

Most servers, fx. nginx, S3, CloudFront, will accept HTTP range requests that are outside the length of the actual content.

While that can perhaps be regarded as bad/unfortunate it is more or less defacto behaviour and as such perhaps it would be best if also sws behave that way.

Because sws does not currently accept these requests I have seen existing solutions that cannot be hosted by sws due to their dependency on servers gracefully handling this.

### Describe the solution you'd like

Allow range request that are out of bounds.

### Describe alternatives you've considered

Make sure implementation(s) are not attempting to do range requests that are out of bounds.

### Build target

All targets

**Comment by joseluisq** [comment]
Just say that I am not opposed to the enhancement.
However, help me to understand it a bit more.
- Can you please share an use case or example(s) when a range request out of bounds could be useful?
- Can you also share a client request example(s) and the expected response(s) using curl?

**Comment by bjornharrtell** [comment]
I'll see if I can provide some requests examples at some point but to give example of a use case is when you want to use http range requests to stream content that consist of multiple parts with unknown size. If you want to do that with minimal amount of roundtrips you would fetch up to a buffer size that might overshoot the size of the content. Current popular web servers and CDN distributions allows this and returns what is available. SWS responds with a HTTP 416 error.

**Comment by joseluisq** [comment]
I understand. It can be useful then.
Basically, the idea is to allow range requests out of bounds but make sure to return what is available in this case.

**Comment by joseluisq** [comment]
Done by #306. It also contains examples of how SWS will behave from now on.
