### ISSUE TITLE
s590x and ppc64le Docker images are missing dependencies

### ISSUE THREAD

**Issue by glehmann** [joseluisq/static-web-server#308]
### Search for duplicate issues

- [X] I already searched, and this issue is not a duplicate.

### Issue scope

Docker / Kubernetes

### Describe the bug

The s590x and ppc64le images are missing dependencies that prevent SWS from running on those platforms

### How to reproduce it

```
$ docker run --rm --platform linux/ppc64le joseluisq/static-web-server --version
ppc64le-binfmt-P: Could not open '/lib64/ld64.so.2': No such file or directory
```
```
$ docker run --rm --platform linux/s390x joseluisq/static-web-server --version
s390x-binfmt-P: Could not open '/lib/ld64.so.1': No such file or directory
````
it works withe all the other platforms
```
$ dk run --rm --platform linux/arm64 joseluisq/static-web-server --version
static-web-server 2.25.0
```

### Expected behavior

well, SWS should work with those platforms

### Complementary information

To give some context, I'm not actually using those platforms. I was looking at some rust projects that I know to find out how they are dealing with multiplatform images, and was surprised that SWS could work with scratch images for non musl targets.

cross don't support the musl targets for those platforms, so I ended up using a different base image for those two platforms in my project: https://github.com/glehmann/yage/blob/1ce059f1bd192a4dbf31a25681f225e509c8a9d7/Earthfile#L69

This is not ideal though as those images are much bigger than the others, and not iso functional.

I've also added a check to make sure the images are actually able to run: https://github.com/glehmann/yage/blob/80e364a083ed31ef250c3396d24585c6c6b0eee7/.github/workflows/docker.yml#L52 . It might be a good idea to have something similar is SWS :-)

### Build target

Docker linux/s390x

### Environment and specs

- [x] **static-web-server:** 2.2.25
- [x] **OS:** ubuntu 23.10
- [x] **Arch:** s590x and ppc64le
- [x] **Docker:** 24.0.5

**Comment by joseluisq** [comment]
@glehmann good catch!
Yes, The SWS binaries for ppc64le (`powerpc64le-unknown-linux-gnu`) and s590x (`s390x-unknown-linux-gnu`) are dynamically linked so it does **not** make so much sense to deliver them with either the Alpine (musl) or the Scratch images (unless they were statically linked, of course).
However, SWS binaries can still be delivered with other Docker images like Debian (glibc).

So what I can suggest is to remove those two (`linux/ppc64le` and `linux/s390x`) from the SWS Alpine and Scratch variants to avoid misunderstanding or future issues and encourage users of those platforms to use the Debian variant instead.
I will take care of this directly.

**Comment by joseluisq** [comment]
> I've also added a check to make sure the images are actually able to run: https://github.com/glehmann/yage/blob/80e364a083ed31ef250c3396d24585c6c6b0eee7/.github/workflows/docker.yml#L52 . It might be a good idea to have something similar is SWS :-)

Sure, we have a [docker ci workflow](https://github.com/static-web-server/static-web-server/blob/master/.github/workflows/devel.docker.yml) that could be adjusted so feel free to suggest something.

**Comment by joseluisq** [comment]
Done by #309
Thanks for reporting!
