### ISSUE TITLE
error: the item `TryFrom` is imported redundantly

### ISSUE THREAD

**Issue by yonas** [joseluisq/static-web-server#317]
### Search for duplicate issues

- [X] I already searched, and this issue is not a duplicate.

### Issue scope

Linux (E.g. Arch Linux, Debian, Alpine, etc)

### Describe the bug

```
   Compiling static-web-server v2.27.0 (/home/yonas/.cargo/git/checkouts/static-web-server-d0678737845d2249/2286e45)
error: the item `TryFrom` is imported redundantly
  --> src/cors.rs:16:33
   |
16 | use std::{collections::HashSet, convert::TryFrom};
   |                                 ^^^^^^^^^^^^^^^^
  --> /rustc/0ecbd0605770f45c9151715e66ba2b3cae367fcb/library/std/src/prelude/mod.rs:129:13
   |
   = note: the item `TryFrom` is already defined here
   |
note: the lint level is defined here
  --> src/lib.rs:99:9
   |
99 | #![deny(warnings)]
   |         ^^^^^^^^
   = note: `#[deny(unused_imports)]` implied by `#[deny(warnings)]`

error: could not compile `static-web-server` (lib) due to 1 previous error
```

### How to reproduce it

1. git clone ...
2. cargo build --release

### Expected behavior

Should compile without error.

### Build target

x86_64-unknown-linux-gnu

### Environment and specs

- [v2.27.0] **static-web-server:**
- [Ubuntu 23] **OS:**
- [x86_64] **Arch:**

**Comment by joseluisq** [comment]
What Rust version are you using?
Because interestingly I built SWS successfully in Debian 12 with Rust 1.75/1.76.

What if you just remove the `std::convert::TryFrom` from `src/cors.rs:16:33`, does it work?

**Comment by yonas** [comment]
> What Rust version are you using?

rustc 1.78.0-nightly (0ecbd0605 2024-02-25)

> What if you just remove the `std::convert::TryFrom` from `src/cors.rs:16:33`, does it work?

Yes.

**Comment by joseluisq** [comment]
I see, then just feel free to submit a patch for nightly.

**Comment by yonas** [comment]
Done. https://github.com/static-web-server/static-web-server/pull/318
