### ISSUE TITLE
add virtual host domain to logging

### ISSUE THREAD

**Issue by hanscees** [joseluisq/static-web-server#322]
### Search for duplicate feature request

- [X] I already searched, and this feature request or improvement is not a duplicate.

### Feature scope

Improve existing functionality

### Describe the solution you'd like

I have installed sws and it works fine for virtual hosts domains. 
Config is like so:
`
[[advanced.virtual-hosts]]
host = "www.hanscees.com"
root = "/var/hanscees"
` 

However, in the logging it is not discernable what domain the logs belong to. 
`
web-1  | 2024-03-01T22:03:40.848154Z  INFO static_web_server::handler: incoming request: method=GET uri=/img/slide-3.jpg remote_addr=[::ffff:192.168.0.2]:43484
`
Please consider adding something to the logging so it becomes clear what domain was involved

### Describe alternatives you've considered

non

### Build target

All targets

**Comment by joseluisq** [comment]
Resolved by https://github.com/static-web-server/static-web-server/pull/442
