### ISSUE TITLE
please add this docker-compose.yml file to docs

### ISSUE THREAD

**Issue by hanscees** [joseluisq/static-web-server#323]
### Search for duplicate issues

- [X] I already searched, and this issue is not a duplicate.

### Issue scope

Linux (E.g. Arch Linux, Debian, Alpine, etc)

### Describe the bug

It is not so much a bug, but an improvement. 

The docker-compose.yml file on your website does not work without a treaffik setup. 
Perhaps you can add my example for people with other setups.

### How to reproduce it

this is the docker-compose.yml working for me 

```
version: "3.3"

services:
  web:
    image: joseluisq/static-web-server:2-alpine
    ports:
      - 80:80
    restart: always
    environment:
      # Note: those envs are customizable but also optional
      - SERVER_CONFIG_FILE=/etc/config.toml
    volumes:
      - ./public:/public
      - ./hanscees_com:/var/hanscees
      - ./etc:/etc

```

### Expected behavior

non

### Complementary information

non

### Build target

aarch64-apple-darwin

### Environment and specs

docker

### Additional context

non

**Comment by joseluisq** [comment]
Sure. In the meantime, if you are curious and want to improve the docs then check out https://github.com/static-web-server/static-web-server/tree/master/docs#build-or-improve-documentation

**Comment by joseluisq** [comment]
Resolved by https://github.com/static-web-server/static-web-server/commit/668ecfedf737fb7dae1080c0cd1382a5541c761c. Check out https://static-web-server.net/features/docker/#docker-compose
