### ISSUE TITLE
Fails to compile without compression feature

### ISSUE THREAD

**Issue by palant** [joseluisq/static-web-server#338]
### Search for duplicate issues

- [X] I already searched, and this issue is not a duplicate.

### Issue scope

Libary (crate)

### Describe the bug

As things are right now, static-web-server cannot be used if the `compression` feature is disabled. Both disabling compression completely and using a specific feature that only enables one compression algorithm will result in compile errors.

### How to reproduce it

1. Create a Rust project.
2. Run `cargo add static-web-server --no-default-features --features compression-gzip` from the command line.
3. Run `cargo build` from the command line.

Compilation fails due to following errors:

```
error[E0609]: no field `compression` on type `cli::General`
  --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/static-web-server-2.28.0/src/testing.rs:31:39
   |
31 |             compression: opts.general.compression,
   |                                       ^^^^^^^^^^^ unknown field
   |
   = note: available fields are: `host`, `port`, `fd`, `threads_multiplier`, `max_blocking_threads` ... and 19 others

error[E0609]: no field `compression_static` on type `cli::General`
  --> ~.cargo/registry/src/index.crates.io-6f17d22bba15001f/static-web-server-2.28.0/src/testing.rs:32:46
   |
32 |             compression_static: opts.general.compression_static,
   |                                              ^^^^^^^^^^^^^^^^^^ unknown field
   |
   = note: available fields are: `host`, `port`, `fd`, `threads_multiplier`, `max_blocking_threads` ... and 19 others
```

That’s because `handler::RequestHandlerOpts` has the `compression` and `compression_static` fields unconditionally, yet in `cli::General` these fields depend on the `compression` feature.

This makes it impossible to disable compression or to select individual compression algorithms in the builds – it always has to be all three of them.

### Expected behavior

The project’s dependencies should compile successfully, both when compression features are disabled and when only one compression algorithm is enabled.

### Build target

x86_64-unknown-linux-gnu

### Environment and specs

- [ ] **static-web-server:** 2.28.0
- [ ] **OS:** Fedora 39
- [ ] **Arch:** x86_64

**Comment by joseluisq** [comment]
Good catch! Yes, we should be able to compile without the `compression`. That's the whole point of using the Cargo compression features.

**Comment by joseluisq** [comment]
Fixed by https://github.com/static-web-server/static-web-server/pull/339

Thanks for reporting!
