### ISSUE TITLE
Directory listing: File sizes wrongly displayed in decimal format

### ISSUE THREAD

**Issue by palant** [joseluisq/static-web-server#370]
### Search for duplicate issues

- [X] I already searched, and this issue is not a duplicate.

### Issue scope

Build target (binary)

### Describe the bug

SWS uses the decimal format for displaying file sizes: 1 KB = 1000 bytes, 1 MB = 1000 MB. This makes no sense.

### How to reproduce it

1. Put a file with 1230 bytes into a directory.
2. Check the directory listing.

The file size will be displayed as “1.23 KB”

### Expected behavior

The file size should be displayed as “1.20 KiB” using the binary format (1 KiB = 1024 bytes). Note that the trailing zero is important to make numbers easier to read, humansize will currently skip it.

### Complementary information

I checked the other web servers. Apache and lighttpd use the binary format, the former not displaying any decimal places. nginx will simply display the raw number.

### Build target

Built from source (specify below)

### Environment and specs

-

### Additional context

I wonder whether the dependency on humansize is worth it. That’s quite a bit of complexity for something that can be done in a few lines of code, and it shows up in the performance graph quite prominently (not as prominently as chrono though).

**Comment by joseluisq** [comment]
Good catch! The `humanize` crate could be even not needed.

**Comment by miroim** [comment]
Hi, can I have a try?

**Comment by joseluisq** [comment]
> Hi, can I have a try?

Sure, unless @palant is working on this?

**Comment by palant** [comment]
Was just about to start but – sure, feel free to.

**Comment by joseluisq** [comment]
@miroim you probably want to also join Discord to coordinate development.

**Comment by joseluisq** [comment]
Closing as resolved by #376
