### ISSUE TITLE
Adjust default compression level

### ISSUE THREAD

**Issue by palant** [joseluisq/static-web-server#380]
### Search for duplicate feature request

- [X] I already searched, and this feature request or improvement is not a duplicate.

### Feature scope

Improve existing functionality

### Feature request related to a problem

SWS currently uses the default compression level, that’s 6 out of 9 for gzip and 11 out of 11 for brotli for example. The defaults are meant for offline compression, not for web servers. Web servers typically use lowest compression level by default (at least nginx and caddy do) because better compression isn’t worth spending so much more CPU time.

### Describe the solution you'd like

SWS should specify compression level explicitly when creating an encoder for dynamic compression. It should pass in `Level::Fastest` by default but making this configurable is a possibility (`--compression-level=fastest|best|default`).

### Describe alternatives you've considered

-

### Build target

All targets

**Comment by palant** [comment]
I did a quick benchmark run just to see what kind of performance change we should expect: https://github.com/palant/static-web-server/actions/runs/8875953447

For a large file with dynamic compression the time went down by 35%, bringing SWS performance on par with nginx. The change is less noticeable for small files and directory listings (around 5%) but still present.

**Comment by gaby** [comment]
@palant How about zstd? It should be using 1 or 3 as default compression.

**Comment by palant** [comment]
> @palant How about zstd? It should be using 1 or 3 as default compression.

That’s a rather theoretical question, isn’t it? I think the only compression algorithms relevant on the web are gzip and brotli.

Either way, going through several layers the default for zstd appears to be 3 (https://github.com/facebook/zstd/blob/97291fc5020a8994019ab76cf0cda83a9824374c/lib/zstd.h#L129).

**Comment by gaby** [comment]
@palant Thats no longer the case, as of 126 Chrome has native zstd support. There's a ticket open for Firefox.

https://github.com/facebook/zstd/releases/tag/v1.5.6

**Comment by palant** [comment]
Just noticed: when we are talking about Brotli, that default level 11 means that time for a single request is measured in *seconds*.

**Comment by palant** [comment]
Going with fastest compression level produced suboptimal file sizes. After [some benchmarking](https://github.com/static-web-server/static-web-server/pull/381#issuecomment-2083490567) I decided that level 4 somehow happens to be a good default for all compression algorithms, so that’s what I now implemented in the PR.

**Comment by joseluisq** [comment]
Closing as resolved by #381

**Comment by joseluisq** [comment]
> @palant Thats no longer the case, as of 126 Chrome has native zstd support. There's a ticket open for Firefox.
> 
> https://github.com/facebook/zstd/releases/tag/v1.5.6

FYI apart from Chrome, Firefox has already support in nightly. https://github.com/mozilla/standards-positions/issues/775#issuecomment-2049605786

And as far as I'm seeing in Chromium's bug tracking, other browsers have already support or they will.
https://issues.chromium.org/issues/40196713

Edit: Safari eventually will support it at some point? https://github.com/WebKit/standards-positions/issues/168#issuecomment-1652198493

**Comment by palant** [comment]
> FYI apart from Chrome, Firefox has already support in nightly. [mozilla/standards-positions#775 (comment)](https://github.com/mozilla/standards-positions/issues/775#issuecomment-2049605786)

That surprised me, given that the corresponding Mozilla bug is still open. Looking into it, that’s apparently initial support which is considered far from done ([bug 1884305](https://bugzilla.mozilla.org/show_bug.cgi?id=1884305) depends on various tasks, and only one of those is resolved). This doesn’t seem to be behind a preference however, I wonder whether zlib is really on track to be released with Firefox 126.
