### ISSUE TITLE
Look for all accepted encodings for precompressed files

### ISSUE THREAD

**Issue by kobutri** [joseluisq/static-web-server#438]
### Search for duplicate feature request

- [X] I already searched, and this feature request or improvement is not a duplicate.

### Feature scope

Improve existing functionality

### Feature request related to a problem

Browsers like Chrome don't provide a relative quality factor for the Accept-Encoding header, but use a fixed order, that does not necessarily express the preference of the browser, but is more likely to ensure backwards compatibility with older web servers. The static-web-server however only checks whether a precompressed file exists for the most preferred, i.e. first accepted encoding.

### Describe the solution you'd like

Keep the same ordering by quality, but look for precompressed files in all accepted encoding standards.

### Describe alternatives you've considered

If no quality order is provided in the header, it might be useful to have the web server choose a quality order, e.g. for precompressed files, based on file size. 

### Build target

All targets

**Comment by joseluisq** [comment]
> Browsers like Chrome don't provide a relative quality factor for the Accept-Encoding header, but use a fixed order, that does not necessarily express the preference of the browser, but is more likely to ensure backwards compatibility with older web servers. The static-web-server however only checks whether a precompressed file exists for the most preferred, i.e. first accepted encoding.

Is there any reference from Chrome docs about this behavior that you can share?
How about also other browsers do they behave the same?

**Comment by kobutri** [comment]
> Is there any reference from Chrome docs about this behavior that you can share? How about also other browsers do they behave the same?

As far as I can tell, they are almost the same.
Chrome: `gzip, deflate, br`
Firefox: `gzip, deflate, br, zstd`
Safari: `gzip, deflate, br`

This was tested on MacOS.

I looked into the chrome a bit further. It always puts them in the same order. [source coude](https://source.chromium.org/chromium/chromium/src/+/main:net/url_request/url_request_http_job.cc;bpv=1;bpt=1;l=688?q=AddExtraHeaders&ss=chromium%2Fchromium%2Fsrc&gsn=AddExtraHeaders&gs=KYTHE%3A%2F%2FKtACCqUBa3l0aGU6Ly9jaHJvbWl1bS5nb29nbGVzb3VyY2UuY29tL2NvZGVzZWFyY2gvY2hyb21pdW0vc3JjLy9tYWluP2xhbmc9YyUyQiUyQj9wYXRoPW5ldC91cmxfcmVxdWVzdC91cmxfcmVxdWVzdF9odHRwX2pvYi5jYyNaUFVtZDk5aVR2WXVTajZqSWtSUnR6N25EeGJvaU4wMnJkRU1VNVlHbEFjCqUBa3l0aGU6Ly9jaHJvbWl1bS5nb29nbGVzb3VyY2UuY29tL2NvZGVzZWFyY2gvY2hyb21pdW0vc3JjLy9tYWluP2xhbmc9YyUyQiUyQj9wYXRoPW5ldC91cmxfcmVxdWVzdC91cmxfcmVxdWVzdF9odHRwX2pvYi5jYyNucUNfV0d4ekRhUVBQMGg0cEhuTWJlQXVQLVRBTlZMM2xneTN2SDFHajI0)
Zstd, will also be enabled soon https://chromestatus.com/feature/6186023867908096
