### ISSUE TITLE
Incorrect Content-Encoding for pre-compressed zstd files

### ISSUE THREAD

**Issue by nomeaning777** [joseluisq/static-web-server#451]
### Search for duplicate issues

- [X] I already searched, and this issue is not a duplicate.

### Issue scope

Library (crate)

### Describe the bug

When serving pre-compressed files using zstd, the Content-Encoding header is set to "zst" instead of the correct "zstd". This causes browsers and other clients to fail to handle the content properly.

### How to reproduce it

1. Start the static-web-server with compression-static enabled and with zstd compressed files. e.g. 
```
echo "Test Content" > index.html
zstd index.html
docker run -p 8080:80 -v "$(pwd):/public" joseluisq/static-web-server:2-debian@sha256:8208279b906b8382d616162a8ba04eda00e4b978fac368c282dfb4cb1bfec136  --compression-static=true
```
2. Access the server with Accept-Encoding set to zstd, and observe that the Content-Encoding is returned as "zst".
```
$ curl 127.0.0.1:8080 -v -H "Accept-Encoding: zstd" --compressed 
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.81.0
> Accept: */*
> Accept-Encoding: zstd
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< last-modified: Wed, 29 May 2024 02:46:36 GMT
< content-type: text/html
< accept-ranges: bytes
< content-encoding: zst
< vary: accept-encoding
< cache-control: public, max-age=86400
< transfer-encoding: chunked
< date: Wed, 29 May 2024 02:46:45 GMT
<
curl: (61) Unrecognized content encoding type. libcurl understands deflate, gzip, br, zstd content encodings.
```

### Expected behavior

The Content-Encoding header should be "zstd".

### Build target

Docker linux/amd64

### Environment and specs

- [x] **static-web-server:** v2.31.1
- [x] **Rust:** v1.78.0
- [x] **OS:** Docker on Ubuntu 22.04
- [x] **Arch:** x86_64 (64-bit)
- [x] **Docker:** 26.1.3-1
- [x] **Client:** curl

### Additional context

This behavior is caused by the precompressed_variant function in src/compression_static.rs.

**Comment by joseluisq** [comment]
Confirmed, The bug fix should come in the next few minutes.

**Comment by joseluisq** [comment]
A patch release should come in the next few days.

Thanks for reporting!
