### ISSUE TITLE
 start as a file server failed

### ISSUE THREAD

**Issue by stardustman** [joseluisq/static-web-server#467]
### Search for duplicate issues

- [X] I already searched, and this issue is not a duplicate.

### Issue scope

macOS

### Describe the bug

I want to start static-web-server(sws) as a file server,but it failed.

### How to reproduce it

use this to start the server

```
sws --port 8888 --root ./build/libs --directory-listing true
error: unexpected argument 'true' found

Usage: sws [OPTIONS]
```

### Expected behavior

start the server sucessfuly

### Complementary information

<img width="876" alt="image" src="https://github.com/user-attachments/assets/1243d3a6-634c-4237-8e4c-f72c039b24b6">

### Build target

aarch64-apple-darwin

### Environment and specs

sws --version
Version:      2.32.1
Built:        2024-07-20 21:33:33 +00:00
Git commit:   97da457bcc87a4a92c94d2cf9488f742a5f178c1
Build target: x86_64-apple-darwin
Rust version: rustc 1.79.0 (129f3b996 2024-06-10)
License:      MIT OR Apache-2.0
Homepage:     https://static-web-server.net
Author:       Jose Quintana <https://joseluisq.net>

**Comment by joseluisq** [comment]
This is a regression reproducible across targets. A bug fix should come in the next few hours.

**Comment by joseluisq** [comment]
Fixed by https://github.com/static-web-server/static-web-server/pull/468

Thanks for reporting!
