### ISSUE TITLE
Does not close using `<ctrl>+c`

### ISSUE THREAD

**Issue by BiswajitThakur** [joseluisq/static-web-server#469]
### Search for duplicate issues

- [X] I already searched, and this issue is not a duplicate.

### Issue scope

Linux (E.g. Arch Linux, Debian, Alpine, etc)

### Describe the bug

I have installed `static-web-server` tool using following command

```curl --proto '=https' --tlsv1.2 -sSfL https://get.static-web-server.net | sh```

my problem is after starting this tool it does not close while i press ```<ctrl>+c``` then ```<ctrl>+d```. it does not work..

I have started server using following command

```
static-web-server -p 8080 -d .
```

```
eagle@hp-lp:~$ static-web-server --version
Version:      2.32.1
Built:        2024-07-20 21:33:33 +00:00
Git commit:   97da457bcc87a4a92c94d2cf9488f742a5f178c1
Build target: x86_64-unknown-linux-gnu
Rust version: rustc 1.79.0 (129f3b996 2024-06-10)
License:      MIT OR Apache-2.0
Homepage:     https://static-web-server.net
Author:       Jose Quintana <https://joseluisq.net>
eagle@hp-lp:~$ uname -a
Linux hp-lp 6.5.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
eagle@hp-lp:~$ which static-
static-sh          static-web-server  
eagle@hp-lp:~$ which static-web-server 
/usr/local/bin/static-web-server
```

I think the above information help to solve the problem

## step 1

```bash
curl --proto '=https' --tlsv1.2 -sSfL https://get.static-web-server.net | sh
```
## step 2

during execution of above command, it ask me for `sudo` password, i entered then it installed successfully.

## step 3

```bash
static-web-server -p 8080 -d .
```

## step 4

Then i enter ``` <ctrl>+c``` to close the server. but it does not close.

### Expected behavior

i press `ctrl+c``` again and again but it does not close the server.

### Complementary information

[Screencast from 08-06-2024 06:40:14 PM.webm](https://github.com/user-attachments/assets/0744027c-86b3-492d-bc7d-607a2e5ad165)

### Build target

x86_64-unknown-linux-gnu

### Environment and specs

- [x] **static-web-server:** [2.32.1]
- [x] **Rust:** [rustc 1.80.0 (051478957 2024-07-21)]
- [x] **OS:** [Ubuntu 22.04.4 LTS]
- [x] **Arch:** [x86_64 (64-bit)]
- [ ] **Docker:** [e.g. 20.10.7]
- [x] **Client:** [Google Chrome 127.0.6533.72]
- [ ] Specify others

**Comment by joseluisq** [comment]
Thanks for the report. This is a known upstream issue that affects all targets-, see https://github.com/static-web-server/static-web-server/issues/335.

The issue happens due to some clients/browsers (e.g. Chrome) could send requests after the server shuts down therefore the server's graceful shutdown process will hang. But if you, for example, press ctrl+c and then go to your browser and refresh the page then SWS will shut down as expected.

We will evaluate to work around this in the near future. I will close this as duplicate, please follow the #335 instead.
