### ISSUE TITLE
Support reverse proxy function

### ISSUE THREAD

**Issue by maaaaz** [joseluisq/static-web-server#489]
### Search for duplicate feature request

- [X] I already searched, and this feature request or improvement is not a duplicate.

### Feature scope

Completely new feature

### Feature request related to a problem

Hello there,

Thanks for this amazing project !

It is so amazing (about performances, config simplicity etc.) that I would like it to have a **simple reverse proxy function**, in order to use SWS as **the main front server**, that can pass requests to app back-end Web servers.

Would it be possible to have a [reverse proxy function](https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html) in SWS ?

Cheers!

### Describe the solution you'd like

cf. above

### Describe alternatives you've considered

cf. above

### Build target

All targets

**Comment by joseluisq** [comment]
Hi, I received several requests why not support reverse proxy functionality in SWS but unfortunately this won't make it as it requires significant effort and increases the complexity of SWS.
I'm not opposed to the idea at all but this is out of scope for now. Who knows if we could revisit this someday.

See my reply to this topic at https://github.com/orgs/static-web-server/discussions/481.

**Comment by maaaaz** [comment]
Thanks, too bad but I understand.
