### ISSUE TITLE
Basic auth

### ISSUE THREAD

**Issue by bjornharrtell** [joseluisq/static-web-server#53]

**Comment by joseluisq** [comment]
Not bad idea at least only for HTTP/2+TLS.

**Comment by bjornharrtell** [comment]
Thanks @joseluisq 🙂 great stuff this little webserver.

**Comment by joseluisq** [comment]
Don't worry, BTW if I can I will try to release it this week.

**Comment by joseluisq** [comment]
Released on [v2.1.0](https://github.com/joseluisq/static-web-server/releases/tag/v2.1.0)
