### ISSUE TITLE
Allow waiting for requests to finish before shutting down

### ISSUE THREAD

**Issue by pdfrod** [joseluisq/static-web-server#61]
**Is your feature request related to a problem? Please describe.**
I'm experimenting with running `static-web-server` on Kubernetes. The issue I'm having is, whenever I deploy a new version of the container running `static-web-server`, some of the HTTP requests made during the deployment are failing. Peeking through the code, it seems that the server doesn't wait for existing requests to complete when it receives the termination signal. I suspect that this is what's causing the issue.

**Describe the solution you'd like**
I'd be nice if the server waited for the existing requests to finish before shutting down. If this behavior is not desirable as default, it could be toggled with some configuration option (e.g. `SERVER_GRACEFUL_SHUTDOWN`, or maybe `SERVER_SHUTDOWN_TIMEOUT`).

**Describe alternatives you've considered**
I was able to workaround the issue by adding a 5 seconds delay before the TERM signal is actually sent to the server. It seems to work, but feels hackish.

**Comment by joseluisq** [comment]
> Peeking through the code, it seems that the server doesn't wait for existing requests to complete when it receives the termination signal. I suspect that this is what's causing the issue.

You're right! In fact is a missing feature.
Yeah, we need to revisit the _gracefull shutdown_ of our internal server implementation (Hyper) for the `v2` (what I assume you are using).

But in general is not a big deal. Even we can add it by default since it should be more reasonable than a new option or env.

**Comment by pdfrod** [comment]
> ...`v2` (what I assume you are using).

Yes, I'm using the `v2` (through the `joseluisq/static-web-server:2` Docker image).

> Even we can add it by default since it should be more reasonable than a new option or env.

Yeah, that's the behavior I'd want 99% of the times, so it makes sense to me that it would be the default.

**Comment by joseluisq** [comment]
The PR #62 will provides this improvement.
However I would like to do a general test via Docker. So I could push a `joseluisq/static-web-server:devel` in order you can give it a test on your environment. Are you able to help me with that?

**Comment by pdfrod** [comment]
Yeah, sure! I can give it a test tomorrow.

**Comment by joseluisq** [comment]
Great!
I will push that changes to Docker Hub as a `devel` tag tomorrow morning (DST).
I will let you know here.

**Comment by joseluisq** [comment]
Let's move the discussion to #62.

**Comment by joseluisq** [comment]
Released on [v2.2.0](https://github.com/joseluisq/static-web-server/releases/tag/v2.2.0)
