### ISSUE TITLE
Working as Windows Service

### ISSUE THREAD

**Issue by bubnenkoff** [joseluisq/static-web-server#65]
I would like to have way install sws as windows service

**Comment by joseluisq** [comment]
Sure.

BTW for a quick solution, you could try a CLI wrapper for Windows Services like https://github.com/mtkennerly/shawl.
I haven't tried it, so it would be great if you could try it for yourself.

**Comment by shirshak55** [comment]
@joseluisq I think nssm works fine but it would be nice if we don't depend on the external things. I think mullvad has a window service installer. Maybe we can add it in the program ourselves so that we can just run this and it works flawlessly on windows?

```
swc install service
```

I expect config.toml file to exist so that we can update service to change root dir etc. I think it might be an arduous task but it depends on what you want.

**Comment by joseluisq** [comment]
> @joseluisq I think nssm works fine but it would be nice if we don't depend on the external things. I think mullvad has a window service installer. Maybe we can add it in the program ourselves so that we can just run this and it works flawlessly on windows?

@shirshak55 yeah that's the idea, don't have external deps. It's not bad to introduce a service command to achieve this. In fact I did a quick look at [mullvad-daemon](https://github.com/mullvad/mullvadvpn-app/blob/master/mullvad-daemon/src/system_service.rs) module and seems something that we could take some ideas from. But open to suggestions and some PR.

> I expect config.toml file to exist so that we can update service to change root dir etc. I think it might be an arduous task but it depends on what you want.

Regarding a config file. It's already in the route map but nothing concrete (like code) yet but yeah it could take some time. More context [here](https://github.com/joseluisq/static-web-server/issues/30#issuecomment-948351606).
So open to suggestions or help of course. Probably we need another "feature request" issue to tackle this feature.

**Comment by joseluisq** [comment]
@shirshak55 

> Regarding a config file. It's already in the route map but nothing concrete (like code) yet but yeah it could take some time. More context [here](https://github.com/joseluisq/static-web-server/issues/30#issuecomment-948351606).
> So open to suggestions or help of course. Probably we need another "feature request" issue to tackle this feature.

Config file setup is under proposal on https://github.com/joseluisq/static-web-server/discussions/69. Feedback welcome!

**Comment by joseluisq** [comment]
Windows service support will be thing on next `v2.9.0` release.

**Comment by joseluisq** [comment]
Released on [v2.9.0](https://github.com/joseluisq/static-web-server/releases/tag/v2.9.0).
