### ISSUE TITLE
Sorting in directory listing

### ISSUE THREAD

**Issue by igoro00** [joseluisq/static-web-server#68]
When using directory listing, files seem to be placed randomly. They're not sorted by name, last modified date, size etc.
It's quite important for my use case(distributing different versions of my app binaries) to show the files and folders ordered.

Could you add buttons in the directory listing page to sort by name, date or size (asc and desc)? Also, adding an env variable/cli argument for the default sorting column would be much appreciated.

**Comment by joseluisq** [comment]
Sure, ordering on directory listing is a "nice to have" feature.

**Comment by joseluisq** [comment]
Released on [v2.3.0](https://github.com/joseluisq/static-web-server/releases/tag/v2.3.0)
