### ISSUE TITLE
How to compile on Linux?

### ISSUE THREAD

**Issue by younicoin** [joseluisq/static-web-server#72]
SWS works fine from compiled file. But I wish to compile by myself. Could you please provide instructions of compilation?

```
git clone https://github.com/joseluisq/static-web-server.git

ls
bors.toml  Cargo.lock  Cargo.toml  CHANGELOG.md  docker  docs  LICENSE-APACHE  LICENSE-MIT  Makefile  Makefile.toml  README.md  sample.env  src  systemd  tests


make
/bin/sh: 1: rustup: not found
    Updating crates.io index
Segmentation fault
    Updating crates.io index
Segmentation fault
make: *** [Makefile:22: install] Error 139

cargo build
error: failed to parse manifest at `/home/user/sws/static-web-server/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  supported edition values are `2015` or `2018`, but `2021` is unknown

cargo -V
cargo 1.42.1

uname -a
Linux devuan 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

cat /etc/os-release 
PRETTY_NAME="Devuan GNU/Linux 3 (beowulf)"
NAME="Devuan GNU/Linux"
VERSION_ID="3"
VERSION="3 (beowulf)"
VERSION_CODENAME=beowulf
ID=devuan
ID_LIKE=debian
HOME_URL="https://www.devuan.org/"
SUPPORT_URL="https://devuan.org/os/community"

```

**Comment by joseluisq** [comment]
> Caused by:
>   supported edition values are `2015` or `2018`, but `2021` is unknown

This project "only" compiles using latest [Rust 2021 Edition](https://github.com/joseluisq/static-web-server/blob/master/Cargo.toml#L23) so first make sure to install Rust [1.56.0](https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html) or higher (or nightly) with the toolchain of your preference. Then just type: `cargo build --release`.

And please don't use the makefile which is intended for development and certain on-demand tasks.
