### ISSUE TITLE
Add trailing slash when missing

### ISSUE THREAD

**Issue by vezaynk** [joseluisq/static-web-server#73]
**Is your feature request related to a problem? Please describe.**
Current, managing relative links is a pain because navigating to `website.com/myfolder` returns the index page of that folder with no redirect. This means that if `index.html` references `./image.png`, the browser will try to get it from `website.com/image.png` instead of `website.com/myfolder/image.png`.

**Describe the solution you'd like**

When serving a folder, check if there is a trailing slash. If there isn't, do a redirect to a path with the slash at the end.

**Comment by joseluisq** [comment]
Yeah in fact we do this already for the directory listing so it should require a minor tweak to make it happen.

**Comment by joseluisq** [comment]
Released on [v2.4.0](https://github.com/joseluisq/static-web-server/releases/tag/v2.4.0)
