### ISSUE TITLE
404 Page not change after server start

### ISSUE THREAD

**Issue by Dexus** [joseluisq/static-web-server#98]
**Describe the bug**
We have started the server, but the 404 error if you use a page that is not there, is only using the page version that is used on start. but not update it while you have changed the complete source.

**To Reproduce**
1. start server
2. open not existing url
3. change 404.html
4. open another not existing url

**Expected behavior**
use the updated 404.html 

**Logs/Screenshots**
If applicable, add logs or screenshots to help explain your problem.

**Environment and Specs**
 - static-web-server: latest
 - OS: Ubuntu 20.04 with docker
 - Docker: latest
 - Client: latest chrome, latest firefox

**Additional context**
Add any other context about the problem here if needed.

**Comment by joseluisq** [comment]
Yeah, but it is kind of on purpose. SWS loads the pages at start up time only.
However we could change that behavior to either load those files right after errors occur or fallback to default errors. In both cases at runtime.

**Comment by prockallsyms** [comment]
Would it be alright to include a static 404 page for different MIME request types? And by default serve those?

**Comment by joseluisq** [comment]
> Would it be alright to include a static 404 page for different MIME request types? And by default serve those?

I didn't get it. Could you show an use case to help me to understand it?

**Comment by talesam** [comment]
I'm uploading the server but I have "404 Not Found" I want the files to appear and I don't expect an html file
